# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # your filter sets are defined here
    filter_sets :

        # use the default cache configuration
        cache : ~

        cards:
            quality: 75

            filters:
                thumbnail : { size : [311, 266], mode: outbound }

        carrousel:
            quality: 75
            filters:
                thumbnail : { size : [838, 568], mode: outbound }
