framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'alertvol@example.com'
            recipients: ['foo@example.com', 'bar@example.com']
        headers:
            from: 'alertvol <alertvol@example.com>'
            bcc: 'wilders@example.com'
            X-Custom-Header: 'foobar'
