vich_uploader:
    db_driver: orm

    mappings:
        annonce_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
        signalement_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
