vich_uploader:
    db_driver: orm

    mappings:
        image_file:
            uri_prefix: /images/products
            upload_destination: '%upload_directory%'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
